Added Dead letter queue  and upgrade to Kafka Connect 2.8.0
university-of-auckland/kafka-http-sink-connector pull request #8
Opened 2021-12-29 11:09 UTC by jomach

2022-01-21 13:40 UTC, nervgh commented
DLQ is one of most important features in my opinon. Thanks @jomach 

So I vote for this PR :+1: 

Here below I've copy-pasted some info about this feature from official docs:

> ### [KIP-610: Error Reporting in Sink Connectors](https://cwiki.apache.org/confluence/display/KAFKA/KIP-610%3A+Error+Reporting+in+Sink+Connectors)
> 
> Extends an Error Reporting capability for sink connectors. Previously, error handling in Kafka Connect included functionality such as retrying, logging, and sending errant records to a dead letter queue. However, the dead letter queue functionality from [KIP-298](https://cwiki.apache.org/confluence/display/KAFKA/KIP-298%3A+Error+Handling+in+Connect) only supports error reporting within contexts of the transform operation, and key, value, and header converter operation. After records are sent to the connector for processing, there is no support for dead letter queue or error reporting functionality. [KIP-610](https://cwiki.apache.org/confluence/display/KAFKA/KIP-610%3A+Error+Reporting+in+Sink+Connectors) allows sink connectors to report individual records as being problematic, and they will be sent to the DLQ. For more information, see [Dead Letter Queue](https://docs.confluent.io/platform/6.0.0/connect/concepts.html#dead-letter-queues).

https://docs.confluent.io/platform/6.0.0/release-notes/index.html#kconnect

2022-01-22 03:43 UTC, danieljimeneznz requested changes

2022-01-22 03:43 UTC, danieljimeneznz commented on pom.xml
> +    <java.version>11</java.version>
Why the bump from Java 8 to Java 11?

2022-01-22 03:43 UTC, danieljimeneznz commented on pom.xml
> +    <kafka.version>2.8.0</kafka.version>
Why the bump from Kafka 2.2.0 to 2.8.0?

2022-01-22 03:43 UTC, danieljimeneznz commented on src/main/java/nz/ac/auckland/kafka/http/sink/handler/DeadLetterQueueHandler.java
> +
```suggestion
```

2022-01-22 03:43 UTC, danieljimeneznz commented on src/main/java/nz/ac/auckland/kafka/http/sink/handler/DeadLetterQueueHandler.java
> +    public void handel(CallBackApiException e) {
`handle` spelt incorrectly?

2022-01-22 03:43 UTC, danieljimeneznz commented on src/main/java/nz/ac/auckland/kafka/http/sink/model/KafkaRecord.java
> +                ", key='" + record.key() + '\'' +
Key is no longer null safe?

2022-01-22 03:43 UTC, danieljimeneznz commented on src/main/java/nz/ac/auckland/kafka/http/sink/request/ApiRequest.java
> +        catch (Exception ex){
Change does nothing apart from remove logging

2022-01-22 03:43 UTC, danieljimeneznz commented on src/main/java/nz/ac/auckland/kafka/http/sink/request/RetryIndicator.java
> +    RETRY(true) , NO_RETRY(false), UNKNOWN(false);
What is changing unknown from true to false doing?

2022-01-22 03:43 UTC, danieljimeneznz commented on src/main/java/nz/ac/auckland/kafka/http/sink/handler/ResponseExceptionStrategyHandlerFactory.java
> +        DEAD_LETTER_QUEUE
Update README with new exception strategy options.

2022-01-22 03:43 UTC, danieljimeneznz commented on src/test/java/nz/ac/auckland/kafka/http/sink/request/ApiRequestTest.java
> +        when(connection.getResponseCode()).thenReturn(502);
Don't understand the 502 change in here?

2022-04-20 13:37 UTC, closed without merging